version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/router-wrapper:${MAPOTEMPO_VERSION:-latest}
    ports:
      - "8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
      - ./poly:/srv/app/poly
    restart: always
    links:
      - redis-cache
      - otp
    environment:
      APP_ENV: production # Swith to "development" for more traces

  otp:
    build:
      context: otp
      args:
        OTP_VERSION: 1.0.0
    image: mapotempo/otp-server:1.0.0
    volumes:
      - ./otp/data:/srv/otp/data

  osrm-car-iceland:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-mt-release-5.5-1-1}
    environment:
      BASENAME: car-iceland
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""
