version: '2'
services:
    builder:
      build: osrm/builder
      image: mapotempo/osrm-builder:latest
      volumes:
        - /srv/osm:/srv/osm
        - /srv/osrm/data:/srv/osrm/data
        - ./osrm/profiles:/srv/osrm/profiles
      links:
        - redis-cache
        - db

    db:
      build: ./postgres
      image: mapotempo/postgres:9.6
      environment:
        POSTGRES_DB: osrm
        POSTGRES_USER: osrm
        POSTGRES_PASSWORD: osrm
      volumes:
        - postgres-9.6:/var/lib/postgres

    redis-cache:
      image: redis:3.2-alpine

volumes:
  postgres-9.6:
