version: '2'
services:
    wrapper:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      image: mapotempo/router-wrapper:latest
      ports:
        - "80:80"
      volumes:
        - ./production.rb:/srv/app/config/environments/production.rb
        - ./poly:/srv/app/poly
      links:
        - redis-cache
        - otp
      environment:
        APP_ENV: production

    otp:
      build:
        context: otp
        args:
          OTP_VERSION: 1.0.0
      image: mapotempo/otp-server:1.0.0
      volumes:
        - /srv/otp/data:/srv/otp/data

    osrm-car-dom:
      build:
        context: osrm/server
      image: mapotempo/osrm-server:latest
      environment:
        REGION: dom
        PROFILE: car
      volumes:
        - /srv/osrm/data:/srv/osrm/data
        - /dev/log:/dev/log

    redis-cache:
        image: redis:alpine
        command: redis-server --save ""
