version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/router-wrapper:${MAPOTEMPO_VERSION:-mweb_v58.0.1}
    ports:
      - "8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./access.rb:/srv/app/config/access.rb
      - ./poly:/srv/app/poly
    restart: always
    links:
      - redis-cache
      - redis-count
    environment:
      PASSENGER_APP_ENV: production
      REDIS_HOST: redis-cache
      REDIS_COUNT_HOST: redis-count

  otp-bordeaux:
    build:
      context: otp
    image: mapotempo/otp-server:${OTP_VERSION:-1.2.0}
    environment:
      GRAPH: bordeaux
    ports:
      - "7001:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: always

  osrm-car-iceland:
    build:
      context: osrm/server
    image: mapotempo/osrm-server:${OSRM_VERSION:-5.21.0}
    environment:
      BASENAME: car-iceland
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: always

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""
    restart: always

  redis-count:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - ./data-count:/data
    command: redis-server --appendonly yes
