#!/bin/bash

set -e

NODE_MODULES=/opt/node_modules

ISOCHRONE_ROOT=$NODE_MODULES/osrm-isochrone-server

cd $ISOCHRONE_ROOT
exec /usr/bin/nodejs $ISOCHRONE_ROOT/server.js --port 6000 --algorithm ${ALGORITHM^^} 2>&1
