name: Tests
on: [push]
jobs:
  test-here-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - name: Cache layers and gems
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
      - name: Check cached gems
        run: |
          echo $(pwd)
          echo $(ls -lh vendor/bundle)
      - name: Install required libs
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential zlib1g-dev zlib1g
          pip3 install flexpolyline
      - name: Bundle ruby
        run: |
          gem install bundler --version 1.17.3
          bundle install --path vendor/bundle --full-index -j $(nproc)
      - name: Ruby test
        run: bundle exec rake test TEST=test/wrappers/here_test.rb
